"""The demo video is published, so its figures are checked like the README's.

Why this file exists
--------------------
``docs/video.html`` is hand-written HTML. Unlike ``docs/index.html`` it is not
generated from the committed recordings, which makes it the one published
surface where a number can drift from the reproducible one with no test
noticing — and it is the surface a judge is most likely to look at, because
it is the submission video.

That gap was real, not theoretical. The first cut of the video printed
"9 of 91 judgements hit a 503", a figure that exists in no manifest and no
README, and printed it beneath the sentence "every figure in this video is
regenerated by the committed test suite". A project whose only claim is that
its numbers can be checked cannot ship a video that claims coverage it does
not have.

So the video now carries the same obligation as the README:

* every rate ``X% (a/b)`` and every interval ``[a%, b%]`` it prints must appear
  verbatim in what the committed recordings actually render;
* its labelled-row counts must match ``labels.csv``;
* the sentence claiming test coverage must stay true — which it now is, because
  these tests exist.

The 503 count is deliberately NOT checked: it comes from one run's log and no
recording records it. The video says so in as many words, and
:func:`test_the_video_does_not_claim_coverage_it_lacks` keeps that admission in
place.
"""

from __future__ import annotations

import ast
import csv
import re
from pathlib import Path

from conftest import REPO_ROOT, TESTSET_DIR

from intentradar.config import Watchlist
from intentradar.eval import EvalDataset, EvalScorer
from intentradar.judge import get_judge
from intentradar.replay import ReplayStore

VIDEO = REPO_ROOT / "docs" / "video.html"
TEMPLATE = REPO_ROOT / "docs" / "template.html"
NARRATION_SRC = REPO_ROOT / "scripts" / "demo" / "narrate.py"
WATCHLIST_PATH = REPO_ROOT / "config" / "watchlist.json"
DATASET_ID = "einprag-2026-09-27"

# The recordings the video's funnel table is drawn from. Both run the same two
# layers, so between them they render every row the table shows.
RECORDINGS = (
    ("einprag-2026-09-27/rule_v4_llm", ("rule_v4", "rule_v4+llm"), 3),
    ("nemotron-openrouter-2026-09-27/rule_v4_llm", ("rule_v4", "rule_v4+llm"), 3),
)

# A rate carries its raw counts, because a bare percentage is what we accuse
# other tools of publishing. An interval is the width of the uncertainty.
_RATE = re.compile(r"\d+(?:\.\d+)?%\s*\(\d+\s*/\s*\d+\)")
_INTERVAL = re.compile(r"\[\d+%,\s*\d+%\]")

# "348 labelled rows ... 312 of them carrying a usable verdict"
_ROWS_TOTAL = re.compile(r"(\d+)\s+labelled rows")
# Three surfaces state this count and they do not word it identically: the
# video says "312 of them carrying a usable verdict", the dashboard badge says
# "312 with a verdict", and the spoken script says "312 with a usable verdict".
# Matching all three phrasings is deliberate — the alternative is one canonical
# sentence, which would mean the guard is checking the wording, not the number.
_ROWS_USABLE = re.compile(
    r"(\d+)\s+(?:of them carrying a usable verdict|with a(?: usable)? verdict)"
)


def _rendered() -> str:
    """Every score table the committed recordings print, concatenated."""
    dataset = EvalDataset.load(DATASET_ID, TESTSET_DIR)
    project = Watchlist.load(WATCHLIST_PATH).get("Einprag")
    out: list[str] = []
    for directory, layers, min_score in RECORDINGS:
        recording = REPO_ROOT / "data" / "replay" / directory
        store = ReplayStore.load(recording)
        judges = [
            get_judge(layer, store=store) if layer.endswith("+llm") else get_judge(layer)
            for layer in layers
        ]
        out.append(
            EvalScorer(judges)
            .score(dataset, project=project, min_score=min_score, replay_banner=store.banner())
            .render()
        )
    return "\n".join(out)


def _body(path: Path) -> str:
    """The visible text of an HTML page: markup and script stripped out."""
    text = path.read_text(encoding="utf-8")
    return re.sub(r"<style>.*?</style>|<script>.*?</script>", " ", text, flags=re.S)


def _narration() -> str:
    """The spoken script, read out of narrate.py's source without importing it.

    ``narrate.py`` imports edge-tts, which is a dev dependency and may be
    absent; parsing the AST instead keeps this guard runnable on a clone that
    only installed the runtime.
    """
    tree = ast.parse(NARRATION_SRC.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.AnnAssign) and getattr(node.target, "id", "") == "NARRATION":
            return " ".join(ast.literal_eval(node.value))
    raise AssertionError(f"NARRATION not found in {NARRATION_SRC}")


def _labelled() -> tuple[int, int]:
    """(rows, usable) across every frozen testset, straight from labels.csv."""
    rows = usable = 0
    for testset in sorted(p.parent.name for p in (REPO_ROOT / "data" / "testset").glob("*/labels.csv")):
        with (REPO_ROOT / "data" / "testset" / testset / "labels.csv").open(encoding="utf-8") as fh:
            labels = [r for r in csv.DictReader(fh)]
        rows += len(labels)
        usable += sum(
            1
            for r in labels
            if (r.get("label") or "").strip() in ("actionable", "not_actionable")
        )
    return rows, usable


def test_every_rate_in_the_video_appears_in_the_rendered_tables() -> None:
    """No number may be typed into the video that the replays do not print.

    The video is the artefact a judge watches; a stale figure there is a stale
    figure on the submission. Checking each rate against the rendered output
    means editing the video's number without re-recording turns the suite red
    rather than shipping quietly.
    """
    if not VIDEO.exists():  # pragma: no cover - ships with the repo
        raise AssertionError(f"missing {VIDEO}")

    # The tool pads its columns, so the rendered table prints "26.3%  (10/38)"
    # with two spaces where the video has one. Collapse runs of whitespace on
    # both sides: we are comparing the figure, not the alignment.
    rendered = re.sub(r"\s+", " ", _rendered())
    body = _body(VIDEO)
    figures = sorted(
        {re.sub(r"\s+", " ", f) for f in _RATE.findall(body)}
        | {re.sub(r"\s+", " ", f) for f in _INTERVAL.findall(body)}
    )

    assert figures, "the video prints no rates at all — the guard has stopped guarding"

    missing = [f for f in figures if f not in rendered]
    assert not missing, (
        "the video prints figures the committed recordings do not:\n  "
        + "\n  ".join(repr(m) for m in missing)
        + "\nEither the video was edited by hand or the recordings were re-made. "
        "Re-record the video in the same commit."
    )


def test_the_spoken_script_states_only_figures_the_replays_print() -> None:
    """The voiceover's numbers are guarded too, not just the on-screen ones.

    A figure spoken over the picture is easier to misquote than one printed on
    it: nobody re-reads it, and it does not appear in the README diff. It is
    checked the same way — every percentage the narration says must be a
    percentage the committed recordings actually render.
    """
    spoken = {float(m) for m in re.findall(r"(\d+(?:\.\d+)?)\s*percent", _narration())}
    assert spoken, "the narration states no percentages — the guard has stopped guarding"

    printed = {float(m) for m in re.findall(r"(\d+(?:\.\d+)?)%", _rendered())}
    unbacked = sorted(spoken - printed)
    assert not unbacked, (
        "the voiceover says percentages the committed recordings do not print: "
        f"{unbacked}. The narration in scripts/demo/narrate.py is hand-written; "
        "re-record the video in the same commit as any change to it."
    )


def test_the_video_states_the_labelled_row_count_correctly() -> None:
    """348 rows / 312 with a verdict — read from labels.csv, not remembered.

    The first version of this line said 313. Nothing caught it, because nothing
    was checking: the count had been carried over by hand from a summary. It is
    now computed the same way every published figure is.
    """
    rows, usable = _labelled()
    assert rows and usable, "no labelled rows found — the testsets did not load"

    for path, text in (
        (VIDEO, _body(VIDEO)),
        (TEMPLATE, _body(TEMPLATE)),
        (NARRATION_SRC, _narration()),
    ):
        totals = {int(m) for m in _ROWS_TOTAL.findall(text)}
        usables = {int(m) for m in _ROWS_USABLE.findall(text)}
        assert totals == {rows}, (
            f"{path.name} says the testsets hold {sorted(totals)} labelled rows; "
            f"labels.csv holds {rows}"
        )
        assert usables == {usable}, (
            f"{path.name} says {sorted(usables)} rows carry a usable verdict; "
            f"labels.csv has {usable} (the rest are borderline, which we refuse "
            "to count as either a hit or a miss)"
        )


def test_the_video_does_not_claim_coverage_it_lacks() -> None:
    """The coverage sentence must stay honest about the one unguarded number.

    The 503 count is not in any manifest, so no test can check it. The video
    admits that. If someone "fixes" the sentence into a blanket claim of test
    coverage, this fails — which is the point: the admission is the guard.
    """
    body = _body(VIDEO)
    assert "503" in body, "the video no longer mentions the retries"

    # Any sentence asserting coverage must not be absolute: it has to name the
    # exception, or it is claiming coverage of a number no test can reach.
    for line in re.split(r"(?<=[.!?])\s+", body):
        if "test suite" in line and re.search(r"\b(every|all)\b", line, re.IGNORECASE):
            assert "503" in line or "not" in line.lower(), (
                "the video claims blanket test coverage:\n  "
                + line.strip()
                + "\nThe 503 count is not covered by any test. Name the exception."
            )
